name: kode_radar
description: A Flutter application for monitoring GitHub and Azure DevOps repositories.
version: 1.0.0+1
homepage: https://github.com/kamilon/kode_radar
repository: https://github.com/kamilon/kode_radar
issue_tracker: https://github.com/kamilon/kode_radar/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.2
  window_manager: ^0.5.1
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  http: ^1.5.0
  cupertino_icons: ^1.0.8
  tray_manager: ^0.5.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png

flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/app_icon.png"
